CREATE DATABASE IF NOT EXISTS PANKAZERO;

USE PANKAZERO;

CREATE TABLE IF NOT EXISTS User (
    idUser INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
